#!/bin/bash
# Build the installable Nextpad++ .rpm — the RPM counterpart of make-deb.sh.
#
# Same recipe as the .deb: a fresh Release configure with the FINAL resource
# path baked in (RESOURCES_DIR is a compile-time literal, so a relocatable
# package MUST be built with the install path), DESTDIR staging, then
# rpmbuild over that staging tree.
#
# Why this can run on Ubuntu at all: we build a BINARY rpm from files that
# are already compiled, so no Fedora-only build machinery is involved. The
# rpm/rpmbuild package in Ubuntu universe supplies everything needed.
#
# Portability across the RPM family: dependencies are AUTO-GENERATED by
# rpmbuild's elfdeps, which emits SONAME requires (libgtk-4.so.1()(64bit)).
# Sonames are identical on every distro, whereas package NAMES are not
# (Fedora "gtk4" vs openSUSE "libgtk-4-1"), so this is the portable form.
#
# Reach of the produced package (measured 2026-08-02): the binary needs
# glibc >= 2.38 and GTK >= 4.14, i.e. Fedora 40+, RHEL/Alma/Rocky 10+,
# openSUSE Leap 16+/Tumbleweed. The RHEL 9 generation cannot run it.
#
# Output: nextpad-plus-plus-<VER>-1.<arch>.rpm in the repo root.
set -euo pipefail
cd "$(dirname "$0")/.."

VER=$(sed -n 's/#define APP_VERSION *"\(.*\)"/\1/p' src/branding.h)
[ -n "$VER" ] || { echo "APP_VERSION not found in src/branding.h" >&2; exit 1; }
command -v rpmbuild >/dev/null || {
    echo "rpmbuild not found — install it with:  sudo apt install rpm" >&2; exit 1; }

ARCH=$(rpm --eval '%{_arch}')          # aarch64 / x86_64 (NOT dpkg's arm64/amd64)

# Memory-aware job cap. An unbounded parallel build once OOM-killed a whole
# desktop session here (~122 lexilla TUs at ~50-60 MB per cc1plus), and the
# build VMs have as little as 1.9 GB. Budget 500 MB per job, never exceed
# nproc. Override with NPP_JOBS=<n>.
if [ -n "${NPP_JOBS:-}" ]; then
    JOBS=$NPP_JOBS
else
    MEM_MB=$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo)
    JOBS=$(nproc); CAP=$(( MEM_MB / 500 )); [ "$CAP" -lt 1 ] && CAP=1
    [ "$JOBS" -gt "$CAP" ] && JOBS=$CAP
fi

STAGE=$(mktemp -d /tmp/npp-rpm-stage-XXXXXX)
TOP=$(mktemp -d /tmp/npp-rpm-top-XXXXXX)
trap 'rm -rf "$STAGE" "$TOP"' EXIT
mkdir -p "$TOP"/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

echo "── Building Nextpad++ $VER ($ARCH, -j$JOBS)"
cmake -B build-pkg -S . \
      -DCMAKE_BUILD_TYPE=Release \
      -DNPP_RES_DIR=/usr/share/nextpad-plus-plus \
      -DCMAKE_INSTALL_PREFIX=/usr
cmake --build build-pkg -j"$JOBS"
DESTDIR="$STAGE" cmake --install build-pkg > /dev/null

# The AppArmor profile is admin-editable config. It is meaningful on
# openSUSE (AppArmor) and inert elsewhere; the scriptlets below are guarded
# so the package installs cleanly on SELinux distros too.
APPARMOR=/etc/apparmor.d/nextpad-plus-plus

# %files, generated from what was actually staged, so the package can never
# silently omit a newly added resource. Directories we own exclusively are
# emitted as %dir entries so they are removed on uninstall.
# Every path is QUOTED: several shipped themes contain spaces ("Black
# board.xml", "Vibrant Ink.xml", …) and rpm splits %files on whitespace.
FILELIST="$TOP/nextpad-files.txt"
( cd "$STAGE"
  find . \( -type f -o -type l \) -printf '"/%P"\n'
  find . -type d -path './usr/share/nextpad-plus-plus*' -printf '%%dir "/%P"\n'
) | sed "s|^\"${APPARMOR}\"$|%config(noreplace) \"${APPARMOR}\"|" | sort > "$FILELIST"
echo "── Staged $(grep -c . "$FILELIST") entries"

cat > "$TOP/SPECS/nextpad-plus-plus.spec" <<SPEC
# Binary spec: the payload is pre-built and handed to rpmbuild via
# --buildroot, so there is no %prep/%build/%install stage.
%define _topdir $TOP
%define _binary_payload w9.gzdio
# Do NOT run the default install post-processing: it would strip the binary
# and rewrite build-ids on an already-finished artifact, making the rpm's
# payload differ from the .deb's for no benefit.
%define __os_install_post %{nil}
%define _build_id_links none
%global __brp_check_rpaths %{nil}

Name:           nextpad-plus-plus
Version:        $VER
Release:        1
Summary:        Multi-tab text editor (Linux port of Notepad++)
License:        GPL-3.0-or-later
URL:            https://nextpad.org
BuildArch:      $ARCH
# unzip: Plugins Admin archive extraction. git: the Git side panel.
Recommends:     unzip
Recommends:     git
# Requires are auto-generated from the ELF payload (soname form) — portable
# across Fedora / RHEL / openSUSE, whose package names differ.
Provides:       nextpad-plus-plus = %{version}-%{release}

%description
Nextpad++ is a native Linux port of the Notepad++ text editor, built on
Scintilla and Lexilla with GTK 4. Multi-tab editing, syntax highlighting
for 50+ languages, user-defined languages, regex find/replace, macros,
session save/restore, auto-backup, dockable side panels, API
autocompletion with calltips, Plugins Admin, and a plugin SDK compatible
with the Nextpad++ macOS port.

%post
/sbin/ldconfig || ldconfig || true
if command -v apparmor_parser >/dev/null 2>&1 && \\
   [ -d /sys/kernel/security/apparmor ] && \\
   [ -f $APPARMOR ]; then
    apparmor_parser -r -T -W $APPARMOR || true
fi
exit 0

%preun
# Unload while the profile file still exists (rpm deletes files before
# %postun runs). \$1 == 0 means final removal, not an upgrade.
if [ "\$1" = "0" ] && command -v apparmor_parser >/dev/null 2>&1 && \\
   [ -d /sys/kernel/security/apparmor ] && \\
   [ -f $APPARMOR ]; then
    apparmor_parser -R $APPARMOR 2>/dev/null || true
fi
exit 0

%postun
/sbin/ldconfig || ldconfig || true
exit 0

%files -f $FILELIST

%changelog
* $(LC_ALL=C date '+%a %b %d %Y') Andrew Letov <aletik@gmail.com> - $VER-1
- Release $VER.
SPEC

rpmbuild -bb "$TOP/SPECS/nextpad-plus-plus.spec" \
         --buildroot "$STAGE" \
         --define "_topdir $TOP" \
         --quiet

OUT="nextpad-plus-plus-${VER}-1.${ARCH}.rpm"
cp "$TOP/RPMS/$ARCH/"*.rpm "./$OUT"
echo "── Built $OUT"
rpm -qp --info "./$OUT" 2>/dev/null | sed -n '1,9p'
echo "── Auto-generated Requires (soname form = portable):"
rpm -qp --requires "./$OUT" 2>/dev/null | grep -vE '^rpmlib' | sed 's/^/     /'
